#! /bin/sh

NAME=interface

case "$1" in
  start)
    printf "Starting $NAME: "
	echo mmc0 > /sys/class/leds/nanopi:blue:status/trigger
	#USB OTG midi/eth/mass storage below
	modprobe libcomposite
	mount -t configfs none /sys/kernel/config
	cd /sys/kernel/config/usb_gadget
	mkdir g1
	cd g1

	echo 0x1d6b > idVendor # Linux Foundation
	echo 0x0104 > idProduct # Multifunction Composite Gadget
	echo 0x0100 > bcdDevice # v1.0.0
	echo 0x0200 > bcdUSB # USB2

	mkdir -p strings/0x409
	echo "fedcba9876543210" > strings/0x409/serialnumber
	echo "DONGLE" > strings/0x409/manufacturer 
	echo "CHANDLE" > strings/0x409/product 

	mkdir -p functions/rndis.usb0
	mkdir -p functions/mass_storage.usb0
	mkdir -p functions/midi.usb0

	FILE=/root/store

	echo 1 > functions/mass_storage.usb0/stall
	echo 0 > functions/mass_storage.usb0/lun.0/cdrom
	echo 0 > functions/mass_storage.usb0/lun.0/ro
	echo 0 > functions/mass_storage.usb0/lun.0/nofua
	echo $FILE > functions/mass_storage.usb0/lun.0/file

	mkdir configs/c.1
	mkdir configs/c.1/strings/0x409

	echo "Config 1: RNDIS network" > configs/c.1/strings/0x409/configuration

	echo 500 > configs/c.1/MaxPower

	ln -s functions/midi.usb0 configs/c.1
	ln -s functions/rndis.usb0 configs/c.1
	ln -s functions/mass_storage.usb0 configs/c.1

	ls /sys/class/udc > UDC
	#USB OTG midi/eth/mass storage above

#	modprobe g_ether #just ethernet
	ifup usb0
	ifup -a #need this for X11 forwarding apparently
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  stop)
    printf "Stopping $NAME: "
	echo none > /sys/class/leds/nanopi:blue:status/trigger
	ifdown usb0
	modprobe -r g_ether
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  restart|reload)
    echo "Restarting $NAME: "
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}" >&2
    exit 1
    ;;
esac

exit 0
