#!/bin/sh
before=`free -m | grep Mem: | awk '{print $3}'`
sync
echo 1 > /proc/sys/vm/drop_caches

after=`free -m | grep Mem: | awk '{print $3}'`

oscsend 127.0.0.1 4000 /oled/aux/erase
oscsend 127.0.0.1 4000 /oled/aux/3 s "RAM before:  $before MB"
oscsend 127.0.0.1 4000 /oled/aux/4 s "RAM after:   $after MB"
oscsend 127.0.0.1 4000 /oled/aux/5 s "RAM saved:   `expr $before - $after` MB"

oscsend 127.0.0.1 4000 /oled/setscreen i 1
exit 0
