#!/bin/sh
oscsend 127.0.0.1 4000 /oled/aux/erase 
oscsend 127.0.0.1 4000 /oled/line/1 s "SHUTTING DOWN"
oscsend 127.0.0.1 4000 /oled/line/2 s "SHUTTING DOWN"
oscsend 127.0.0.1 4000 /oled/line/3 s "SHUTTING DOWN"
oscsend 127.0.0.1 4000 /oled/line/4 s "SHUTTING DOWN"
oscsend 127.0.0.1 4000 /oled/line/5 s "SHUTTING DOWN"
oscsend 127.0.0.1 4000 /oled/line/6 s "SHUTTING DOWN"

oscsend 127.0.0.1 4000 /oled/setscreen i 1
oscsend 127.0.0.1 4000 /oled/setscreen i 1
oscsend 127.0.0.1 4000 /oled/setscreen
halt
exit 0
